### ISSUE TITLE
Ineffective use of systems concepts.

### ISSUE THREAD

**Issue by jonalf** [tchen00/MKS65-FinalProject#1]
At face value, this doesn't seem to use systems concepts effectively. Why would shared memory be used to store login information & a leaderboard? Those are things that should persist and thus not live in memory. The systems concepts should be used effectively, and should not seem as if they were added because you need to have them somewhere.

**Comment by ayao00** [comment]
Login information and user history stats will now just be the implementation of reading in files and appending whenever a new user joins the game. We have also added a twist on Minesweeper, making it multiplayer and therefore utilizing networking for two users. If there is still a lack of systems concept utilized, we will improvise and update you with any changes to our project.

**Comment by jonalf** [comment]
approved.

make it so.
